version: "3.8"

services:
  dev:
    container_name: capstone-container
    build:
      context: .
      dockerfile: devcontainer/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "25223:22"
      - "8080:8080"  # Spring Boot

  fastapi:
    container_name: fastapi-server
    build:
      context: ./fastapi-server     # FastAPI 디렉토리 따로 생성
      dockerfile: Dockerfile        # FastAPI용 Dockerfile
    ports:
      - "8000:8000"                 # FastAPI 기본 포트
    volumes:
      - ./fastapi-server:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
