version: "3.8"

services:
  dev:
    container_name: capstone-container
    build:
      context: .
      dockerfile: devcontainer/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "25223:22"             # SSH 접속용 포트 포워딩
      - "8080:8080"            # Spring Boot 외부 접근을 위한 포트 포워딩
    networks:
      - capstone-net
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"   # REST API
    #  - "6334:6334"   # Web UI
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - capstone-net

networks:
  capstone-net:

volumes:
  qdrant_data:



# docker exec -it capstone-container bash
# http://localhost:6333/dashboard
      - "25223:22"
      - "8080:8080"  # Spring Boot

  fastapi:
    container_name: fastapi-server
    build:
      context: ./fastapi-server     # FastAPI 디렉토리 따로 생성
      dockerfile: Dockerfile        # FastAPI용 Dockerfile
    ports:
      - "8000:8000"                 # FastAPI 기본 포트
    volumes:
      - ./fastapi-server:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
