spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://Capstone:csd25-1qwe@cluster0.ars7meo.mongodb.net/Longevity_Meals?retryWrites=true&w=majority
server.port=8080
server.address=0.0.0.0

#테서랙트 주소 수정 필요
tesseract.datapath=/usr/share/tesseract-ocr/4.00/tessdata

# 특정 패키지의 로그 레벨을 DEBUG로 설정
logging.level.root=INFO
logging.level.com.capstone.backend.service=DEBUG


# 전체 로그 레벨 설정 (선택)
# logging.level.root=INFO
# 한글 UTF-8 설정
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

logging.level.org.springframework.web=INFO
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# langchain api url 설정(아마 변경 필요)
langchain.api.url=http://localhost:8000/api/gpt/mealplan


# 하늘 추가
# mongodb shell 접속
# mongosh "mongodb+srv://Capstone:csd25-1qwe@cluster0.ars7meo.mongodb.net/Longevity_Meals"
# use Longevity_Meals

# 구글 클라우드 설정
google.cloud.project-id=${GOOGLE_CLOUD_PROJECT_ID:top-decoder-472914-d8}
google.cloud.credentials.path=/app/top-decoder-472914-d8-249692a4059f.json
google.document.project-id=${GOOGLE_CLOUD_PROJECT_ID:top-decoder-472914-d8}
google.document.location=${GOOGLE_DOCUMENT_LOCATION:us}
google.document.processor-id=${GOOGLE_DOCUMENT_PROCESSOR_ID:68a488b957e3a06c}

